# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/SPCC_1TB/Projects/ha-mini-console/ui/blinds_panel_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BlindsPanel(object):
    def setupUi(self, BlindsPanel):
        print("blinds panel setup")
        BlindsPanel.setObjectName("BlindsPanel")
        BlindsPanel.resize(626, 480)
        self.widget = QtWidgets.QWidget(BlindsPanel)
        self.widget.setGeometry(QtCore.QRect(30, 40, 168, 92))
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("Cancel")
        self.pushButton.setText('Cancel')
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 0, 3)
        # self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        # self.pushButton_2.setObjectName("pushButton_2")
        # self.gridLayout_2.addWidget(self.pushButton_2, 1, 1, 1, 1)
        # self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        # self.pushButton_3.setObjectName("pushButton_3")
        # self.gridLayout_2.addWidget(self.pushButton_3, 2, 0, 1, 1)

        self.retranslateUi(BlindsPanel)
        QtCore.QMetaObject.connectSlotsByName(BlindsPanel)

    def retranslateUi(self, BlindsPanel):
        _translate = QtCore.QCoreApplication.translate
        BlindsPanel.setWindowTitle(_translate("BlindsPanel", "Blinds"))
        self.pushButton.setText(_translate("BlindsPanel", "PushButton"))
        # self.pushButton_2.setText(_translate("BlindsPanel", "PushButton"))
        # self.pushButton_3.setText(_translate("BlindsPanel", "PushButton"))
