# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_panel_frame.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPanel(object):
    def setupUi(self, MainPanel):
        MainPanel.setObjectName("MainPanel")
        MainPanel.resize(640, 480)
        self.lightsButton = QtWidgets.QPushButton(MainPanel)
        self.lightsButton.setGeometry(QtCore.QRect(330, 60, 300, 190))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lightsButton.sizePolicy().hasHeightForWidth())
        self.lightsButton.setSizePolicy(sizePolicy)
        self.lightsButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"color: rgb(15, 12, 90);\n"
"background-color: rgb(124, 255, 105);\n"
"font: 48pt \".AppleSystemUIFont\";")
        self.lightsButton.setObjectName("lightsButton")
        self.blindsButton = QtWidgets.QPushButton(MainPanel)
        self.blindsButton.setGeometry(QtCore.QRect(10, 60, 300, 190))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blindsButton.sizePolicy().hasHeightForWidth())
        self.blindsButton.setSizePolicy(sizePolicy)
        self.blindsButton.setStyleSheet("background-color: rgb(95, 102, 255);\n"
"font: 128pt \".AppleSystemUIFont\";\n"
"color: rgb(255, 238, 254);")
        self.blindsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("blinds-horizontal.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.blindsButton.setIcon(icon)
        self.blindsButton.setIconSize(QtCore.QSize(128, 128))
        self.blindsButton.setObjectName("blindsButton")
        self.statusButton = QtWidgets.QPushButton(MainPanel)
        self.statusButton.setGeometry(QtCore.QRect(330, 260, 300, 190))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusButton.sizePolicy().hasHeightForWidth())
        self.statusButton.setSizePolicy(sizePolicy)
        self.statusButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 57, 126);\n"
"font: 48pt \".AppleSystemUIFont\";")
        self.statusButton.setObjectName("statusButton")
        self.temperaturButton = QtWidgets.QPushButton(MainPanel)
        self.temperaturButton.setGeometry(QtCore.QRect(10, 260, 300, 190))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temperaturButton.sizePolicy().hasHeightForWidth())
        self.temperaturButton.setSizePolicy(sizePolicy)
        self.temperaturButton.setStyleSheet("color: rgb(55, 58, 255);\n"
"color: rgb(239, 243, 255);\n"
"font: 48pt \".AppleSystemUIFont\";\n"
"background-color: rgb(226, 67, 255);\n"
"")
        self.temperaturButton.setObjectName("temperaturButton")

        self.retranslateUi(MainPanel)
        QtCore.QMetaObject.connectSlotsByName(MainPanel)

    def retranslateUi(self, MainPanel):
        _translate = QtCore.QCoreApplication.translate
        MainPanel.setWindowTitle(_translate("MainPanel", "Guest Room"))
        self.lightsButton.setText(_translate("MainPanel", "Lights"))
        self.statusButton.setText(_translate("MainPanel", "Status"))
        self.temperaturButton.setText(_translate("MainPanel", "Temperature"))
